export const MapboxMapStyles = [
	'standard',
	'streets-v12',
	'outdoors-v12',
	'light-v11',
	'dark-v11',
	'satellite-v9',
	'satellite-streets-v12',
	'navigation-day-v1',
	'navigation-night-v1',
] as const;

export const CustomMapStyles = ['ezequielm/cij7hk832007dapktzdyaemih'] as const;

export const OldMapHideableLayerNames = [
	'background',
	'landuse',
	'landcover',
	'waterway',
	'countriesJaggedLine',
	'water',
	'water copy',
	'landuse_park',
	'hillshade',
	'oceanDepth_1000',
	'oceanDepth_2000',
	'oceanDepth_3000',
	'oceanDepth_5000',
	'oceanDepth_6000',
	'iceShelves',
	'road_major',
	'building',
	'tunnel_minor',
	'tunnel_major',
	'road_minor',
	'bridge_minor_case',
	'bridge_major_case',
	'bridge_minor',
	'bridge_major',
	'countriesEdgesBlur',
	'countriesLines',
	'countriesInnerBorders',
	'countries_jaggedLinePattern',
	'poi_label',
	'road_major_label',
	'place_label_other',
	'place_label_city',
	'country_label',
	'marine-label',
] as const;
